# SMTP Mail Server Configuration
mail.smtp.host=sandbox.smtp.mailtrap.io
mail.smtp.port=2525
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.username=ee978934f03c4f
mail.smtp.password=0da162ae9533cb
mail.from.email=noreply@gymcenter.com
mail.from.name=GCMS System
